**Q1. What are the benefits of the built-in array package, if any?**

Multiple data elements of the same kind can be represented by a single array. The index number in an array allows for arbitrary access to its elements. Memory regions for an array's components are allocated in a single block. As a result, there is zero room for error in the memory allocation process when dealing with arrays. Because to this, memory shortages and overflows in arrays are prevented.

**Q2. What are some of the array package&#39;s limitations?**

An array's size should be determined before it's created. A static structure, an array (which means the array is of fixed size). The size of an array cannot be changed once it has been declared. The amount of memory allotted to it is fixed and cannot be altered.Because the elements of an array are stored in successive memory regions and the shifting operation is expensive, insertion and deletion are both quite challenging.

Wasteful memory allocation results in wasted space, while insufficient allocation causes issues as well.

**Q3. Describe the main differences between the array and numpy packages.**

In contrast to NumPy, which provides a wide range of numerical operations, the array package does not provide any assistance with numerical calculation with the elements inside it in number form.Contrast this with numpy, which can have more than one dimension, and you'll see that arrays only carry numerical data in one dimension.Accessing an item in an array is a simple matter of looking up its index, whereas with numpy you'll need to look up its index in both the column and row. This also applies to the appending operation.

While a tabular structure is not formed in the case of array, one is formed in numpy.

**Q4. Explain the distinctions between the empty, ones, and zeros functions.**

**Here are some key differences between the zero, one, and empty functions:**

**Empty Function:**A function that does nothing is said to be "empty," or to have "no body." Python will throw an error if you try to define a function without including any statements. As such, we employ a pass statement to prevent that from happening. An exceptional statement in Python, pass, has no effect. It's a useless statement except in that role.


**Ones Function:** Values of 1 are returned by this function, which creates a new array of the specified size and data type with all elements set to 1.


**Zeros Function:** Values of 0 are returned by this function, which creates a new array of the specified size and data type with all of its elements set to 0.

**Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?**

Its purpose is to apply the function to each coordinate, producing an array as a result. The rank of shape determines how many parameters can be passed to the function. Array coordinates along a given axis are represented by individual parameters.

**Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?**

If an integer scaler value is added to a numpy array, that value will be propagated to each element of the array.

In [3]:
import numpy as np
a=np.arange(6).reshape(2,3)
print(a)
print()
print(a+1)


[[0 1 2]
 [3 4 5]]

[[1 2 3]
 [4 5 6]]


Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome? 

It'll carry out the procedure as instructed by the humans. So, the + operator will cause an addition to be made to the current array, whereas the * operator will cause a multiplication to be made.

**Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?**

Including a string of known length in a numpy array is certainly possible. Any numpy array that stores strings uses the maximum length of the longest string in the array as its dtype. Once this value is set, the array can only store strings whose length is less than or equal to the value specified. Reassigning a string value that is longer than the longest existing element causes all values longer than the limit to be discarded, up to but not including the longest value.

Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

When applied to the same position, it merely adds or multiplies the elements together.

**Q10. What is the best way to use a Boolean array to mask another array?**

The masked where function in the numpy package is the most efficient way to use a Boolean array to hide the contents of another array.

**Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.**

**Following are three ways to get SD**
1. np.std
2. using math module
3. without using any package

In [9]:
import math
import numpy as np
x = [1,2]
SD = np.std(x)
print(SD)

0.5


In [10]:
import math
import sys

def sd_calc(data):
    n = len(data)

    if n <= 1:
        return 0.0

    mean, sd = avg_calc(data), 0.0

    # calculate stan. dev.
    for el in data:
        sd += (float(el) - mean)**2
    sd = math.sqrt(sd / float(n-1))

    return sd

def avg_calc(ls):
    n, mean = len(ls), 0.0

    if n <= 1:
        return ls[0]

    # calculate average
    for el in ls:
        mean = mean + float(el)
    mean = mean / float(n)

    return mean

data = [4, 2, 5, 8, 6]
print("Sample Data: ",data)
print("Standard Deviation : ",sd_calc(data))

Sample Data:  [4, 2, 5, 8, 6]
Standard Deviation :  2.23606797749979


In [12]:
a = a=np.arange(9).reshape(3,3)
avg = a
N = 1
SD = (((1-avg)**2 + (2-avg)**2)/N)**1/2
print(SD)

[[ 2.5  0.5  0.5]
 [ 2.5  6.5 12.5]
 [20.5 30.5 42.5]]


**12. What is the dimensionality of a Boolean mask-generated array?**

It will have same dimensionality as input array.